version: '2.0'

services:
  nest:
    image: nest
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/container/app
    depends_on:
      - jboss
    ## set your startup file here
    command:  nodemon --inspect=0.0.0.0:9229 main.js
  jboss:
    image: jboss
    build: ./vulapps/jboss
    environment:
      JBOSS_PASS: admin123
    ports:
      - 8000:8000