#https://stackoverflow.com/questions/20845056/how-can-i-expose-more-than-1-port-with-docker
#https://github.com/docker/compose/pull/1827
version: '2.0'

services:
  nest:
    image: nest
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3001:3000
      - 9229:9229
    volumes:
      - .:/container/app
    depends_on:
      - jboss
      - jexboss
    links:
      - jboss
      - jexboss
    ## set your startup file here
    command:  nodemon --inspect=0.0.0.0:9229 main.js
  jboss:
    image: gastrodia/jboss:as-6.1.0 
    ports:
      - 9990:9990
      - 8080:8080
  jexboss:
    image: gastrodia/jexboss
    ports:
      - 9000:3000
  # jboss:
  #   #image: jboss
  #   image: medicean/vulapps:j_jboss_1
  #   #image: tutum/jboss:as7    #compose will pull image ,if it not exist
  #   #build: ./vulapps/jboss
  #   #build: tutum/jboss:as7
  #   environment:
  #     JBOSS_PASS: admin123
  #   ports:
  #     - 8080:8080

