FROM gastrodia/node

# 设置镜像作者
MAINTAINER gastrodia <gastrodia@outlook.com>

ADD sources.list /etc/apt/sources.list


# 安装 wget
RUN apt-get update && RUN apt-get install -y python python-dev python-distribute python-pip


